import { useRouter } from 'next/router'
import Link from 'next/link'
import { Formik, Form, Field, ErrorMessage } from 'formik';
import * as Yup from "yup";
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import Head from 'next/head'

const SignupSchema = Yup.object().shape({
  name: Yup.string()
    .min(2, 'Too Short!')
    .max(70, 'Too Long!')
    .required('Required'),
  email: Yup.string()
    .email('Invalid email')
    .required('Required'),
});


const Sample = () => {
  return (
    <>

<div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Formik
       initialValues={{
         name: '',
         email: '',
       }}
       validationSchema={SignupSchema}
       onSubmit={values => {
         console.log(values);
       }}
     >
       {({ errors, touched }) => (
         <Form>
          <div>
           <Field name="name"  />
            {errors.name && touched.name ? (
             <div>{errors.name}</div>
           ) : null}
          <ErrorMessage name="name" />
          </div>
          <div>
           <Field name="email" type="email" />
            {errors.email && touched.email ? (
             <div>{errors.email}</div>
           ) : null}
         <ErrorMessage name="email" />
           </div>
           <button type="submit">Submit</button>
         </Form>
       )}
     </Formik>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>

    </>
  )
}

export default Sample