import { useRouter } from 'next/router'
import Link from 'next/link'
import { Formik, Form, Field, ErrorMessage } from 'formik';
import * as Yup from "yup";
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import Head from 'next/head'

const SignupSchema = Yup.object().shape({
  password: Yup.string()
    .min(2, 'Too Short!')
    .max(70, 'Too Long!')
    .required('Required'),
  username: Yup.string()
    .email('Invalid username')
    .required('Required'),
});


const Sample = () => {
  return (
    <>

<div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Formik
       initialValues={{
        password: '',
         username: '',
       }}
       validationSchema={SignupSchema}
       onSubmit={values => {
         console.log(values);
        var response =   fetch('api/token', {
          method: "POST",
          headers: {
            "Content-Type": "application/json"
          },
              body: JSON.stringify(values),
            }).then((res) => res.json())
            .then((data) => {
              console.log(data);
            });


       }}
     >
       {({ errors, touched }) => (
         <Form>
          <div>
           <Field name="password"  />
            {errors.password && touched.password ? (
             <div>{errors.password}</div>
           ) : null}
          <ErrorMessage name="password" />
          </div>
          <div>
           <Field name="username" type="username" />
            {errors.username && touched.username ? (
             <div>{errors.username}</div>
           ) : null}
          <ErrorMessage name="username" />
           </div>
           <button type="submit">Submit</button>
         </Form>
       )}
     </Formik>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>

    </>
  )
}

export default Sample